os:
  - linux
  - osx

# JRuby isn't working on the new default distribution
dist: trusty

language: ruby
rvm:
  - 2.3
  - 2.5
  - 2.7
  - jruby-9.1.7.0

gemfile:
  - testing/gemfiles/gherkin9.gemfile
  - testing/gemfiles/gherkin10.gemfile
  - testing/gemfiles/gherkin11.gemfile
  - testing/gemfiles/gherkin12.gemfile
  - testing/gemfiles/gherkin13.gemfile
  - testing/gemfiles/gherkin14.gemfile
  - testing/gemfiles/gherkin15.gemfile
  - testing/gemfiles/gherkin16.gemfile
  - testing/gemfiles/gherkin17.gemfile
  - testing/gemfiles/gherkin18.gemfile
  - testing/gemfiles/gherkin19.gemfile

matrix:
  exclude:

    # Older versions of Ruby don't seem to work on Travis CI for OSX. The Linux
    # testing is probably good enough for the older versions.
    - rvm: 2.3
      os: osx

# TODO: Remove this once TravisCI fixes their bundler issue (https://github.com/alphagov/govuk_template/pull/186)
before_install:
  - gem install bundler -v '< 2'

script: bundle exec rake cuke_modeler:ci_build
