version: '1.0.{build}'

environment:
  matrix:

    # Gherkin 9.x+ requires at least Ruby 2.3
    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin9.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin9.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin9.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin9.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin10.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin10.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin10.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin10.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin11.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin11.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin11.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin11.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin12.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin12.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin12.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin12.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin13.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin13.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin13.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin13.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin14.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin14.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin14.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin14.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin15.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin15.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin15.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin15.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin16.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin16.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin16.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin16.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/gherkin17.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin17.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/gherkin17.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/gherkin17.gemfile

# Allow Windows builds to use CRLF as expected by linting tools, etc.
init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake cuke_modeler:ci_build
